<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RsyncWindows.Core\RsyncWindows.Core.csproj" />
    <ProjectReference Include="..\RsyncWindows.Transports\RsyncWindows.Transports.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>rsyncWindows</AssemblyName> <!-- user-facing binary name: rsyncWindows.exe -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationIcon>..\..\assets\rsyncWindows.ico</ApplicationIcon>
    <Version>2.0.1</Version>
    <Authors>Jose Rodriguez Arroyo</Authors>
    <Company>Jose Rodriguez Arroyo</Company>
    <Product>rsyncWindows</Product>
  </PropertyGroup>

</Project>
